# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_genred <- function(input, param) {
    .Call(`_binder_r_genred`, input, param)
}

test_binder <- function() {
    .Call(`_binder_test_binder`)
}

